apiVersion: v1
kind: ConfigMap

metadata:
  name: demo-content
  namespace: wazuh-cloud

data:
  index.html: |
    Hello, I'm learning the Git workflows & ConfigMap as well as verifying the detail, and it is Version 3
