name: Deploy Demo App

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Show Hostname
        run: hostname

      - name: Verify Cluster
        run: kubectl get nodes

      - name: Verify Deployment
        run: kubectl get deployment -n wazuh-cloud

      - name: Verify Pods
        run: kubectl get pods -n wazuh-cloud
